before_install:
- sudo apt-get install doxygen graphviz
- openssl aes-256-cbc -K $encrypted_82da6839b977_key -iv $encrypted_82da6839b977_iv
  -in travisci_rsa.enc -out config/travisci_rsa -d
- chmod 0600 config/travisci_rsa
- cp config/travisci_rsa ~/.ssh/id_rsa
- "./config/publish-doxygen"
